language: node_js
node_js:
  - '0.10'
  - '0.11'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-mongoose-plugin' ]; then cd .. && eval "mv $currentfolder generator-mongoose-plugin" && cd generator-mongoose-plugin; fi
matrix:
  fast_finish: true
  allow_failures:
    - node_js: '0.11'
